global:
  ssmPrefix: /k8s/eks-demo

postgresql:
  primary:

    # Docker Official PostgreSQL applies these flags to existing data directories.
    args: ["-c", "max_connections=350", "-c", "shared_buffers=256MB", "-c", "effective_cache_size=1GB", "-c", "work_mem=4MB"]


    persistence:
      size: 20Gi

      storageClass: gp3


