app:
  configmap:
    data:
      CLUSTER_NAME: 'eks-demo-b'
      MESSAGE: hello world
      PROFILE: 'demo'
  routing:
    hosts:
    - sample-grpc.demo.opspresso.com
    httpRoute:
      enabled: true
  podLabels:
    sidecar.istio.io/inject: "true"
  podAnnotations:
    link.argocd.argoproj.io/external-link: https://sample-grpc.demo.opspresso.com
  serviceMonitor:
    enabled: true
    labels:
      release: prometheus-eks-demo