app:
  configmap:
    data:
      VERSION: v0.66.1
    enabled: true
  env:
  - name: ENV_HASH
    value: 36ed9c8d59463d0ee64c27b09c533b0f
  - name: VERSION
    value: v0.66.1
  externalSecrets:
    data:
    - key: /k8s/common/agentdure/better-auth-secret
      name: BETTER_AUTH_SECRET
    - key: /k8s/common/agentdure/google-client-id
      name: GOOGLE_CLIENT_ID
    - key: /k8s/common/agentdure/google-client-secret
      name: GOOGLE_CLIENT_SECRET
    - key: /k8s/common/agentdure/llm-api-key
      name: LLM_API_KEY
    - key: /k8s/common/agentdure/llm-provider-openai-api-key
      name: LLM_PROVIDER_OPENAI_API_KEY
    - key: /k8s/common/agentdure/llm-provider-anthropic-api-key
      name: LLM_PROVIDER_ANTHROPIC_API_KEY
    - key: /k8s/common/agentdure/llm-provider-xai-api-key
      name: LLM_PROVIDER_XAI_API_KEY
    - key: /k8s/common/agentdure/llm-provider-openrouter-api-key
      name: LLM_PROVIDER_OPENROUTER_API_KEY
    - key: /k8s/common/agentdure/aes-encryption-key
      name: AES_ENCRYPTION_KEY
    - key: /k8s/common/agentdure/a2a-api-key
      name: A2A_API_KEY
    - key: /k8s/common/agentdure/github-token
      name: GITHUB_TOKEN
    - key: /k8s/common/agentdure/schedule-scan-token
      name: SCHEDULE_SCAN_TOKEN
    enabled: true
  image:
    tag: v0.66.1
