app:
  env:
  - name: ENV_HASH
    value: 4f90fca8b8673e0b7a50a28f58e891b1
  - name: VERSION
    value: v0.10.0
  externalSecrets:
    data:
    - key: /k8s/common/mcp-memory/database-url
      name: DATABASE_URL
  image:
    tag: v0.10.0
