apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mcp-brave-search-local
  namespace: argocd
  labels:
    app.kubernetes.io/instance: apps-local-demo
    opspresso.com/cluster: local-demo
    opspresso.com/group: apps
spec:
  project: apps
  destination:
    name: in-cluster
    namespace: agent-mcps
  source:
    repoURL: https://github.com/opspresso/argocd-env-demo
    targetRevision: HEAD
    path: charts/mcp-brave-search
    helm:
      valueFiles:
      - values.yaml
      - values-alpha.yaml
      - local/values-local-demo.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
