app:
  replicaCount: 1
  autoscaling:
    enabled: False

  resources: null

  configmap:
    data:
      CLUSTER_NAME: 'k3s-demo'
      HOSTNAME: sample.svc.cluster.local
      MESSAGE: hello world
      PROFILE: 'k3s'
      PROTOCOL: http
      REDIS_HOST: redis-master
      REDIS_PORT: '6379'
  routing:
    hosts:
    - sample-node.demo.opsp.dev
    httpRoute:
      enabled: true

      parentRefs:
        - name: traefik-gateway
          namespace: traefik-gateway


  podAnnotations:
    link.argocd.argoproj.io/external-link: https://sample-node.demo.opsp.dev
  serviceMonitor:
    enabled: false
    labels:
      release: prometheus-k3s-demo
  externalSecrets:
    data:
    - key: /k8s/common/sample-node/redis-password
      name: REDIS_PASS

  workloads:
    thumbs:
      env:
        - name: COUNTER_URL
          value: https://sample-node.demo.opsp.dev/counter/

redis:
  istio:
    sidecar:
      inject: true

  resources: null
  master:
    resources: null
