apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-k3s
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: noti-argocd-k3s
  labels:
    app.kubernetes.io/instance: apps-k3s-demo
    opspresso.com/cluster: k3s-demo
    opspresso.com/group: apps
spec:
  project: apps
  ignoreDifferences:
  - group: ""
    kind: PersistentVolumeClaim
    name: minio
    jsonPointers:
    - /spec/resources/requests/storage
  source:
    repoURL: https://github.com/opspresso/argocd-env-demo
    targetRevision: HEAD
    path: charts/minio
    helm:
      valueFiles:
      - values.yaml
  destination:
    name: in-cluster
    namespace: agent-studio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
