apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: neo4j-k3s
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: noti-argocd-k3s
  labels:
    app.kubernetes.io/instance: apps-k3s-demo
    opspresso.com/cluster: k3s-demo
    opspresso.com/group: apps
spec:
  project: apps
  ignoreDifferences:
  - group: apps
    kind: StatefulSet
    name: memory-neo4j
    jsonPointers:
    - /spec/volumeClaimTemplates
  source:
    repoURL: https://github.com/opspresso/argocd-env-demo
    targetRevision: HEAD
    path: charts/neo4j
    helm:
      valueFiles:
      - values.yaml
      - k3s/values-k3s-demo.yaml
  destination:
    name: in-cluster
    namespace: agent-memory
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
