app:
  replicaCount: 1
  autoscaling:
    enabled: False

  resources: null

  configmap:
    data:
      CLUSTER_NAME: 'k3s-demo'
      MESSAGE: hello world
      PROFILE: 'k3s'
  routing:
    hosts:
    - sample-grpc.demo.opsp.dev
    httpRoute:
      enabled: true

      parentRefs:
        - name: traefik-gateway
          namespace: traefik-gateway


  podAnnotations:
    link.argocd.argoproj.io/external-link: https://sample-grpc.demo.opsp.dev
  serviceMonitor:
    enabled: true
    labels:
      release: prometheus-eks-demo