app:
  additionalLabels:
    department: apps
  configmap:
    data:
      CLUSTER_NAME: eks-demo
      HOSTNAME: sample.svc.cluster.local
      MESSAGE: hello world
      PROFILE: alpha
      PROTOCOL: http
      VERSION: v0.10.21
    enabled: true
  env:
  - name: ENV_HASH
    value: 6269de7fef4609956ef1ae693feac58f
  - name: VERSION
    value: v0.10.21
  image:
    tag: v0.10.21
  routing:
    hosts:
    - sample-spring.demo.nalbam.com
    httpRoute:
      enabled: true
  podLabels:
    sidecar.istio.io/inject: "true"
