app:
  replicaCount: 1
  autoscaling:
    enabled: false

  resources: null



  configmap:
    enabled: true
    data:
      AWS_REGION: ap-northeast-2
      AWS_PROFILE: "default"
      AWS_CONFIG_FILE: /aws/config
      AWS_SHARED_CREDENTIALS_FILE: /aws/credentials
  extraVolumes:
    - name: local-aws-config
      hostPath:
        path: "/Users/nalbam/.aws/config"
        type: File
    - name: local-aws-credentials
      hostPath:
        path: "/Users/nalbam/.aws/credentials"
        type: File
  extraVolumeMounts:
    - name: local-aws-config
      mountPath: /aws/config
      readOnly: true
    - name: local-aws-credentials
      mountPath: /aws/credentials
      readOnly: true
