apiVersion: v2
name: minio
description: MinIO for the k3s Agent Platform
type: application
version: v1.0.0
appVersion: 2025.7.23

dependencies:
  - name: minio
    repository: https://charts.bitnami.com/bitnami
    version: 17.0.21
