minio:
  fullnameOverride: minio

  global:
    security:
      allowInsecureImages: true

  image:
    repository: bitnamilegacy/minio
  clientImage:
    repository: bitnamilegacy/minio-client

  mode: standalone
  defaultBuckets: agent-studio-static,agent-memory

  auth:
    rootUser: agent-studio
    existingSecret: minio-credentials
    rootUserSecretKey: root-user
    rootPasswordSecretKey: root-password

  persistence:
    enabled: true
    size: 10Gi

  resourcesPreset: none
  resources: null
  console:
    image:
      repository: bitnamilegacy/minio-object-browser
    resourcesPreset: none
    resources: null
  defaultInitContainers:
    volumePermissions:
      resourcesPreset: none
      resources: null
  provisioning:
    resourcesPreset: none
    resources: null
