minio:
  fullnameOverride: minio

  mode: standalone
  defaultBuckets: agent-studio-static,agent-memory

  auth:
    rootUser: agent-studio
    existingSecret: minio-credentials
    rootUserSecretKey: root-user
    rootPasswordSecretKey: root-password

  persistence:
    enabled: true
    size: 10Gi

  resourcesPreset: none
  resources: null
  console:
    resourcesPreset: none
    resources: null
  defaultInitContainers:
    volumePermissions:
      resourcesPreset: none
      resources: null
  provisioning:
    resourcesPreset: none
    resources: null
