app:
  configmap:
    data:
      VERSION: v0.28.18
    enabled: true
  env:
  - name: ENV_HASH
    value: a19b73fc2bec1450c267aace203d5fab
  - name: VERSION
    value: v0.28.18
  image:
    tag: v0.28.18
