app:
  configmap:
    data:
      VERSION: v0.28.14
    enabled: true
  env:
  - name: ENV_HASH
    value: 78f4b6e0a93383ef452202d693209aba
  - name: VERSION
    value: v0.28.14
  image:
    tag: v0.28.14
