app:
  configmap:
    data:
      VERSION: v0.28.17
    enabled: true
  env:
  - name: ENV_HASH
    value: 424b47a76fd012350757924c736cbde8
  - name: VERSION
    value: v0.28.17
  image:
    tag: v0.28.17
