app:
  configmap:
    data:
      VERSION: v0.30.0
    enabled: true
  env:
  - name: ENV_HASH
    value: ca056d4f73be2d2ab81c2bb66ff76ccc
  - name: VERSION
    value: v0.30.0
  image:
    tag: v0.30.0
