app:
  configmap:
    data:
      VERSION: v0.29.2
    enabled: true
  env:
  - name: ENV_HASH
    value: 3b452ff7d60e2a9e1330264ae8b49d43
  - name: VERSION
    value: v0.29.2
  image:
    tag: v0.29.2
