app:
  replicaCount: 1
  autoscaling:
    enabled: False

  resources: null

  configmap:
    enabled: true
    data:
      STAGE: 'prod'
      ADMIN_EMAILS: me@nalbam.com
      # ALLOWED_EMAIL_DOMAINS: nalbam.com
      AWS_REGION: ap-northeast-2
      BETTER_AUTH_URL: https://memory.demo.opsp.dev
  routing:
    hosts:
    - memory.demo.opsp.dev
    httpRoute:
      enabled: true
  podLabels:
    sidecar.istio.io/inject: "true"
  podAnnotations:
    link.argocd.argoproj.io/external-link: https://memory.demo.opsp.dev

  serviceMonitor:
    labels:
      release: prometheus-k3s-demo