app:
  configmap:
    data:
      CLUSTER_NAME: '{{cluster}}'
      MESSAGE: hello world
      PROFILE: '{{env}}'
  routing:
    hosts:
    - sample-grpc.{{hostname.public}}
    httpRoute:
      enabled: true
  podLabels:
    sidecar.istio.io/inject: "true"
  podAnnotations:
    link.argocd.argoproj.io/external-link: https://sample-grpc.{{hostname.public}}
  serviceMonitor:
    enabled: true
    labels:
      release: prometheus-eks-demo
