ssmPrefix: /k8s/local-demo

minio:

  defaultBuckets: agent-studio,agent-memory


  persistence:
    size: 5Gi


  resources: null
  resourcesPreset: none


  autoscaling:
    vpa:
      enabled: false


  console:

    enabled: False


    resources: null
    resourcesPreset: none


    autoscaling:
      vpa:
        enabled: false
      hpa:
        enabled: false