ssmPrefix: /k8s/k3s-demo

minio:


  persistence:
    size: 10Gi


  resources: null
  resourcesPreset: none


  autoscaling:
    vpa:
      enabled: false


  console:


    resources: null
    resourcesPreset: none


    autoscaling:
      vpa:
        enabled: false
      hpa:
        enabled: false