app:
  autoscaling:
    enabled: true
    maxReplicas: 6
    minReplicas: 2
  configmap:
    data:
      VERSION: v0.16.3
    enabled: true
  env:
  - name: ENV_HASH
    value: f6629dcf417e6547109f0ca9e760d422
  - name: VERSION
    value: v0.16.3
  externalSecrets:
    data:
    - key: /k8s/common/slack-token
      name: slack-token
    - key: /k8s/common/sample-node/redis-password
      name: REDIS_PASS
    enabled: true
  image:
    tag: v0.16.3
