app:
  autoscaling:
    enabled: true
    maxReplicas: 12
    minReplicas: 2
  configmap:
    data:
      VERSION: v0.15.12
    enabled: true
  env:
  - name: ENV_HASH
    value: 40302d83d6ffff7d01d9d1a3c2a1205f
  - name: VERSION
    value: v0.15.12
  externalSecrets:
    data:
    - key: /k8s/common/slack-token
      name: slack-token
    - key: /k8s/common/sample-node/redis-password
      name: REDIS_PASS
    enabled: true
  image:
    tag: v0.15.12
