app:
  autoscaling:
    enabled: true
    maxReplicas: 12
    minReplicas: 2
  configmap:
    data:
      VERSION: v0.15.5
    enabled: true
  env:
  - name: ENV_HASH
    value: a61335405c070f580a7e9b8152d969c4
  - name: VERSION
    value: v0.15.5
  externalSecrets:
    data:
    - key: /k8s/common/slack-token
      name: slack-token
    - key: /k8s/common/sample-node/redis-password
      name: REDIS_PASS
    enabled: true
  image:
    tag: v0.15.5
