app:
  autoscaling:
    enabled: true
    maxReplicas: 6
    minReplicas: 2
  configmap:
    data:
      VERSION: v0.16.7
    enabled: true
  env:
  - name: ENV_HASH
    value: 85a4c6e68f72c099a95307ab2bb10f8b
  - name: VERSION
    value: v0.16.7
  externalSecrets:
    data:
    - key: /k8s/common/slack-token
      name: slack-token
    - key: /k8s/common/sample-node/redis-password
      name: REDIS_PASS
    enabled: true
  image:
    tag: v0.16.7
