app:
  autoscaling:
    enabled: true
    maxReplicas: 24
    minReplicas: 2
  configmap:
    data:
      VERSION: v0.15.4
    enabled: true
  env:
  - name: ENV_HASH
    value: c9d2e51c9f9b3dc7355eb42c593cc89c
  - name: VERSION
    value: v0.15.4
  externalSecrets:
    data:
    - key: /k8s/common/slack-token
      name: slack-token
    - key: /k8s/common/sample-node/redis-password
      name: REDIS_PASS
    enabled: true
  image:
    tag: v0.15.4
