app:
  configmap:
    data:
      VERSION: v0.133.1
    enabled: true
  env:
  - name: ENV_HASH
    value: 6356acfee6b06f97887a70cf8629c845
  - name: VERSION
    value: v0.133.1
  image:
    tag: v0.133.1
