app:
  configmap:
    data:
      VERSION: v0.140.2
    enabled: true
  env:
  - name: ENV_HASH
    value: c1393bea0c0a257804f3825953bfda80
  - name: VERSION
    value: v0.140.2
  image:
    tag: v0.140.2
