app:
  configmap:
    data:
      VERSION: v0.125.0
    enabled: true
  env:
  - name: ENV_HASH
    value: b9c017a1d6eb6454e0092a104cdfbf0f
  - name: VERSION
    value: v0.125.0
  image:
    tag: v0.125.0
