app:
  configmap:
    data:
      VERSION: v0.116.2
    enabled: true
  env:
  - name: ENV_HASH
    value: 4a787384b313c623e8bef2f71e4bce70
  - name: VERSION
    value: v0.116.2
  image:
    tag: v0.116.2
