app:
  configmap:
    data:
      VERSION: v0.118.0
    enabled: true
  env:
  - name: ENV_HASH
    value: 0c1ebd8e6d535a6a34331927c854c467
  - name: VERSION
    value: v0.118.0
  image:
    tag: v0.118.0
