app:
  configmap:
    data:
      VERSION: v0.115.1
    enabled: true
  env:
  - name: ENV_HASH
    value: 67b8ce6a55781ef959d4654d884f6571
  - name: VERSION
    value: v0.115.1
  image:
    tag: v0.115.1
