app:
  replicaCount: 1
  autoscaling:
    enabled: True
  image:
    repository: 396608815058.dkr.ecr.ap-northeast-2.amazonaws.com/agent-memory


  configmap:
    enabled: true
    data:
      STAGE: 'prod'
      ADMIN_EMAILS: me@nalbam.com
      # ALLOWED_EMAIL_DOMAINS: nalbam.com
      AWS_REGION: ap-northeast-2
      BETTER_AUTH_URL: https://memory.demo.opspresso.com
  routing:
    hosts:
    - memory.demo.opspresso.com
    httpRoute:
      enabled: true


  podLabels:
    sidecar.istio.io/inject: "true"

  podAnnotations:
    link.argocd.argoproj.io/external-link: https://memory.demo.opspresso.com

  serviceMonitor:
    labels:
release: prometheus-eks-demo-b
